/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author llean
 */
public class IFrmTablero extends javax.swing.JInternalFrame {

    private JLabel[] labels;

    /**
     * Creates new form IFrmTablero
     */
    public IFrmTablero() {
        initComponents();
        this.labels = new JLabel[76];
        inicializarTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Matriz = new javax.swing.JPanel();

        Matriz.setBackground(new java.awt.Color(11, 88, 132));
        Matriz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 5));
        Matriz.setPreferredSize(new java.awt.Dimension(840, 278));
        Matriz.setLayout(new java.awt.GridLayout(5, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Matriz, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Matriz, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarTablero() {
        Matriz.removeAll();
        
        for (int i = 1; i <= 75; i++) {
            JLabel label = new JLabel(String.valueOf(i), SwingConstants.CENTER);
            label.setFont(new Font("Arial", Font.PLAIN, 36));
            label.setForeground(new Color(220, 197, 156));
            label.setOpaque(true);
            label.setBackground(new Color(11, 88, 132));
            label.setBorder(BorderFactory.createLineBorder(new Color(214, 204, 179), 3));
            
            labels[i] = label;
            Matriz.add(label);
        }
        
        Matriz.revalidate();
        Matriz.repaint();
    }
    
    public void marcarNumero(int numero) {
        if (numero >= 1 && numero <= 75) {
            JLabel label = labels[numero];
            label.setBackground(new Color(220, 197, 157));
            label.setForeground(new Color(11,88,132));
            label.setFont(new Font("Arial", Font.PLAIN, 36));
        }
    }
    
     public void reiniciar() {
        for (int i = 1; i <= 75; i++) {
            labels[i].setBackground(new Color(11, 88, 132));
            labels[i].setForeground(new Color(220,197, 156));
            labels[i].setFont(new Font("Arial", Font.PLAIN, 36));
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Matriz;
    // End of variables declaration//GEN-END:variables
}
