/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Controladores.ControladorPrincipal;
import Exceptions.NumeroInvalidoExcepcion;

/**
 *
 * @author llean
 */
public class IFrmTombolaManual extends javax.swing.JInternalFrame {

        private ControladorPrincipal controlador;
    /**
     * Creates new form IFrmTombola
     */
    public IFrmTombolaManual(ControladorPrincipal controlador) {
        this.controlador = controlador;
        initComponents();
    }
    
    
    public void actualizarUltimoNumero(int numero) {
        lblSecundario.setText(String.valueOf(numero));
        lblSecundario.repaint();
    }
    
    private void ingresarNumeroManual(){
        String numeroTexto = txtPrincipal.getText().trim();
        try {
            controlador.getControladorPartida().procesarNumeroManual(numeroTexto);
            txtPrincipal.setText("");
            txtPrincipal.requestFocus();
            
        } catch (NumeroInvalidoExcepcion ex) {
            ex.getMessage();
            txtPrincipal.setText("");
            txtPrincipal.requestFocus();
        }
    }
    
    public void reiniciar() {
        txtPrincipal.setText("");
        lblSecundario.setText("");
        txtPrincipal.setEnabled(true);
        btnIngresar.setEnabled(true);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrincipal = new javax.swing.JTextField();
        lblSecundario = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(540, 540));

        txtPrincipal.setBackground(new java.awt.Color(229, 207, 163));
        txtPrincipal.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        txtPrincipal.setForeground(new java.awt.Color(21, 84, 108));
        txtPrincipal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrincipal.setText("20");
        txtPrincipal.setBorder(null);

        lblSecundario.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblSecundario.setForeground(new java.awt.Color(21, 85, 124));
        lblSecundario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnIngresar.setBackground(new java.awt.Color(21, 86, 126));
        btnIngresar.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(226, 201, 151));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(null);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TombolaManual.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(txtPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Fondo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(lblSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Fondo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        ingresarNumeroManual();
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblSecundario;
    private javax.swing.JTextField txtPrincipal;
    // End of variables declaration//GEN-END:variables
}
