/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author llean
 */
public class IFrmModo extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmModo
     */
    public IFrmModo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManual = new javax.swing.JButton();
        btnAutomatico = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManual.setBackground(new java.awt.Color(240, 215, 167));
        btnManual.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        btnManual.setForeground(new java.awt.Color(32, 101, 137));
        btnManual.setText("Manual");
        btnManual.setBorder(null);
        getContentPane().add(btnManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 320, 50));

        btnAutomatico.setBackground(new java.awt.Color(240, 215, 167));
        btnAutomatico.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        btnAutomatico.setForeground(new java.awt.Color(32, 101, 137));
        btnAutomatico.setText("Automatico");
        btnAutomatico.setBorder(null);
        getContentPane().add(btnAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 320, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnAutomatico;
    private javax.swing.JButton btnManual;
    // End of variables declaration//GEN-END:variables
}
