/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author llean
 */
public class IFrmCartonManual extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmCaronManual
     */
    public IFrmCartonManual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Matriz = new javax.swing.JPanel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        btnSubir = new javax.swing.JButton();
        txt14 = new javax.swing.JTextField();
        txt15 = new javax.swing.JTextField();
        txt16 = new javax.swing.JTextField();
        txt17 = new javax.swing.JTextField();
        txt18 = new javax.swing.JTextField();
        txt19 = new javax.swing.JTextField();
        txt20 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        txt23 = new javax.swing.JTextField();
        txt24 = new javax.swing.JTextField();
        txt25 = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Matriz.setBackground(new java.awt.Color(240, 210, 145));
        Matriz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 77, 43), 5));
        Matriz.setLayout(new java.awt.GridLayout(5, 5));

        txt1.setBackground(new java.awt.Color(240, 210, 145));
        txt1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt1.setForeground(new java.awt.Color(183, 71, 38));
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setText("75");
        txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt1.setOpaque(true);
        Matriz.add(txt1);

        txt2.setBackground(new java.awt.Color(240, 210, 145));
        txt2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt2.setForeground(new java.awt.Color(183, 71, 38));
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2.setText("1");
        txt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt2.setOpaque(true);
        Matriz.add(txt2);

        txt3.setBackground(new java.awt.Color(240, 210, 145));
        txt3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt3.setForeground(new java.awt.Color(183, 71, 38));
        txt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt3.setText("1");
        txt3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt3.setOpaque(true);
        Matriz.add(txt3);

        txt4.setBackground(new java.awt.Color(240, 210, 145));
        txt4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt4.setForeground(new java.awt.Color(183, 71, 38));
        txt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt4.setText("1");
        txt4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt4.setOpaque(true);
        Matriz.add(txt4);

        txt5.setBackground(new java.awt.Color(240, 210, 145));
        txt5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt5.setForeground(new java.awt.Color(183, 71, 38));
        txt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt5.setText("1");
        txt5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt5.setOpaque(true);
        Matriz.add(txt5);

        txt6.setBackground(new java.awt.Color(240, 210, 145));
        txt6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt6.setForeground(new java.awt.Color(183, 71, 38));
        txt6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt6.setText("1");
        txt6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt6.setOpaque(true);
        Matriz.add(txt6);

        txt7.setBackground(new java.awt.Color(240, 210, 145));
        txt7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt7.setForeground(new java.awt.Color(183, 71, 38));
        txt7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt7.setText("1");
        txt7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt7.setOpaque(true);
        Matriz.add(txt7);

        txt8.setBackground(new java.awt.Color(240, 210, 145));
        txt8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt8.setForeground(new java.awt.Color(183, 71, 38));
        txt8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt8.setText("1");
        txt8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt8.setOpaque(true);
        Matriz.add(txt8);

        txt9.setBackground(new java.awt.Color(240, 210, 145));
        txt9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt9.setForeground(new java.awt.Color(183, 71, 38));
        txt9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt9.setText("1");
        txt9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt9.setOpaque(true);
        Matriz.add(txt9);

        txt10.setBackground(new java.awt.Color(240, 210, 145));
        txt10.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt10.setForeground(new java.awt.Color(183, 71, 38));
        txt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt10.setText("1");
        txt10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt10.setOpaque(true);
        Matriz.add(txt10);

        txt11.setBackground(new java.awt.Color(240, 210, 145));
        txt11.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt11.setForeground(new java.awt.Color(183, 71, 38));
        txt11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt11.setText("1");
        txt11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt11.setOpaque(true);
        Matriz.add(txt11);

        txt12.setBackground(new java.awt.Color(240, 210, 145));
        txt12.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt12.setForeground(new java.awt.Color(183, 71, 38));
        txt12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt12.setText("1");
        txt12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt12.setOpaque(true);
        Matriz.add(txt12);

        btnSubir.setBackground(new java.awt.Color(184, 72, 39));
        btnSubir.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnSubir.setForeground(new java.awt.Color(240, 210, 145));
        btnSubir.setText("Subir");
        btnSubir.setBorder(null);
        btnSubir.setOpaque(true);
        Matriz.add(btnSubir);

        txt14.setBackground(new java.awt.Color(240, 210, 145));
        txt14.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt14.setForeground(new java.awt.Color(183, 71, 38));
        txt14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt14.setText("1");
        txt14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt14.setOpaque(true);
        Matriz.add(txt14);

        txt15.setBackground(new java.awt.Color(240, 210, 145));
        txt15.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt15.setForeground(new java.awt.Color(183, 71, 38));
        txt15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt15.setText("1");
        txt15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt15.setOpaque(true);
        Matriz.add(txt15);

        txt16.setBackground(new java.awt.Color(240, 210, 145));
        txt16.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt16.setForeground(new java.awt.Color(183, 71, 38));
        txt16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt16.setText("1");
        txt16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt16.setOpaque(true);
        Matriz.add(txt16);

        txt17.setBackground(new java.awt.Color(240, 210, 145));
        txt17.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt17.setForeground(new java.awt.Color(183, 71, 38));
        txt17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt17.setText("1");
        txt17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt17.setOpaque(true);
        Matriz.add(txt17);

        txt18.setBackground(new java.awt.Color(240, 210, 145));
        txt18.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt18.setForeground(new java.awt.Color(183, 71, 38));
        txt18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt18.setText("1");
        txt18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt18.setOpaque(true);
        Matriz.add(txt18);

        txt19.setBackground(new java.awt.Color(240, 210, 145));
        txt19.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt19.setForeground(new java.awt.Color(183, 71, 38));
        txt19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt19.setText("1");
        txt19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt19.setOpaque(true);
        Matriz.add(txt19);

        txt20.setBackground(new java.awt.Color(240, 210, 145));
        txt20.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt20.setForeground(new java.awt.Color(183, 71, 38));
        txt20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt20.setText("1");
        txt20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt20.setOpaque(true);
        Matriz.add(txt20);

        txt21.setBackground(new java.awt.Color(240, 210, 145));
        txt21.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt21.setForeground(new java.awt.Color(183, 71, 38));
        txt21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt21.setText("1");
        txt21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt21.setOpaque(true);
        Matriz.add(txt21);

        txt22.setBackground(new java.awt.Color(240, 210, 145));
        txt22.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt22.setForeground(new java.awt.Color(183, 71, 38));
        txt22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt22.setText("1");
        txt22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt22.setOpaque(true);
        Matriz.add(txt22);

        txt23.setBackground(new java.awt.Color(240, 210, 145));
        txt23.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt23.setForeground(new java.awt.Color(183, 71, 38));
        txt23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt23.setText("1");
        txt23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt23.setOpaque(true);
        Matriz.add(txt23);

        txt24.setBackground(new java.awt.Color(240, 210, 145));
        txt24.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt24.setForeground(new java.awt.Color(183, 71, 38));
        txt24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt24.setText("1");
        txt24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt24.setOpaque(true);
        Matriz.add(txt24);

        txt25.setBackground(new java.awt.Color(240, 210, 145));
        txt25.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txt25.setForeground(new java.awt.Color(183, 71, 38));
        txt25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt25.setText("1");
        txt25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 72, 40), 5));
        txt25.setOpaque(true);
        Matriz.add(txt25);

        getContentPane().add(Matriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 520, 400));

        Fondo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carton.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel Matriz;
    private javax.swing.JButton btnSubir;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt15;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt17;
    private javax.swing.JTextField txt18;
    private javax.swing.JTextField txt19;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt23;
    private javax.swing.JTextField txt24;
    private javax.swing.JTextField txt25;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
