/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Controladores.ControladorPrincipal;

/**
 *
 * @author llean
 */
public class IFrmCartonBuilder extends javax.swing.JInternalFrame {
    
    private ControladorPrincipal controlador;
    private FrmDesktopPane desktop;
    /**
     * Creates new form IFrmCartonBuilder
     */
    public IFrmCartonBuilder(ControladorPrincipal controlador,
            FrmDesktopPane desktop) {
        this.controlador = controlador;
        this.desktop = desktop;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblanadir = new javax.swing.JLabel();
        lblAuto = new javax.swing.JLabel();
        lblCarton1 = new javax.swing.JLabel();
        btnAuto = new javax.swing.JButton();
        lblManual = new javax.swing.JLabel();
        lblCarton2 = new javax.swing.JLabel();
        btnManual = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(33, 101, 137));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblanadir.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblanadir.setForeground(new java.awt.Color(237, 210, 163));
        lblanadir.setText("Añadir:");
        jPanel1.add(lblanadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 6, -1, -1));

        lblAuto.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblAuto.setForeground(new java.awt.Color(34, 101, 138));
        lblAuto.setText("Auto");
        lblAuto.setToolTipText("");
        jPanel1.add(lblAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        lblCarton1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblCarton1.setForeground(new java.awt.Color(34, 101, 138));
        lblCarton1.setText("Carton");
        jPanel1.add(lblCarton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 150, -1));

        btnAuto.setBackground(new java.awt.Color(232, 211, 164));
        btnAuto.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        btnAuto.setForeground(new java.awt.Color(34, 101, 138));
        btnAuto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 211, 164), 1, true));
        btnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 200, 180));

        lblManual.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblManual.setForeground(new java.awt.Color(34, 101, 138));
        lblManual.setText("Manual");
        jPanel1.add(lblManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lblCarton2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblCarton2.setForeground(new java.awt.Color(34, 101, 138));
        lblCarton2.setText("Carton");
        jPanel1.add(lblCarton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 90, 150, -1));

        btnManual.setBackground(new java.awt.Color(232, 211, 164));
        btnManual.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnManual.setForeground(new java.awt.Color(34, 101, 138));
        btnManual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 211, 164), 1, true));
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });
        jPanel1.add(btnManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoActionPerformed
        controlador.getControladorCartones().agregarCartonAutomatico();
        getCantidadCartones();
    }//GEN-LAST:event_btnAutoActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
       controlador.getControladorCartones().abrirCreacionCartonManual();
    }//GEN-LAST:event_btnManualActionPerformed

    public int getCantidadCartones(){
        int cantidad = controlador.getGestorJuego().getCantidadCartones();
        return cantidad;
    }
    
    private void cerrarFrame(){
        this.setVisible(false);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuto;
    private javax.swing.JButton btnManual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAuto;
    private javax.swing.JLabel lblCarton1;
    private javax.swing.JLabel lblCarton2;
    private javax.swing.JLabel lblManual;
    private javax.swing.JLabel lblanadir;
    // End of variables declaration//GEN-END:variables
}
