/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author llean
 */
public class IFrmTablero extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmTablero
     */
    public IFrmTablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        N1 = new javax.swing.JLabel();
        N2 = new javax.swing.JLabel();
        N3 = new javax.swing.JLabel();
        N4 = new javax.swing.JLabel();
        N5 = new javax.swing.JLabel();
        N6 = new javax.swing.JLabel();
        N7 = new javax.swing.JLabel();
        N8 = new javax.swing.JLabel();
        N9 = new javax.swing.JLabel();
        N10 = new javax.swing.JLabel();
        N11 = new javax.swing.JLabel();
        N12 = new javax.swing.JLabel();
        N13 = new javax.swing.JLabel();
        N14 = new javax.swing.JLabel();
        N15 = new javax.swing.JLabel();
        N16 = new javax.swing.JLabel();
        N17 = new javax.swing.JLabel();
        N18 = new javax.swing.JLabel();
        N19 = new javax.swing.JLabel();
        N20 = new javax.swing.JLabel();
        N21 = new javax.swing.JLabel();
        N22 = new javax.swing.JLabel();
        N23 = new javax.swing.JLabel();
        N24 = new javax.swing.JLabel();
        N25 = new javax.swing.JLabel();
        N26 = new javax.swing.JLabel();
        N27 = new javax.swing.JLabel();
        N28 = new javax.swing.JLabel();
        N29 = new javax.swing.JLabel();
        N30 = new javax.swing.JLabel();
        N31 = new javax.swing.JLabel();
        N32 = new javax.swing.JLabel();
        N33 = new javax.swing.JLabel();
        N34 = new javax.swing.JLabel();
        N35 = new javax.swing.JLabel();
        N36 = new javax.swing.JLabel();
        N37 = new javax.swing.JLabel();
        N38 = new javax.swing.JLabel();
        N39 = new javax.swing.JLabel();
        N40 = new javax.swing.JLabel();
        N41 = new javax.swing.JLabel();
        N42 = new javax.swing.JLabel();
        N43 = new javax.swing.JLabel();
        N44 = new javax.swing.JLabel();
        N45 = new javax.swing.JLabel();
        N46 = new javax.swing.JLabel();
        N47 = new javax.swing.JLabel();
        N48 = new javax.swing.JLabel();
        N49 = new javax.swing.JLabel();
        N50 = new javax.swing.JLabel();
        N51 = new javax.swing.JLabel();
        N52 = new javax.swing.JLabel();
        N53 = new javax.swing.JLabel();
        N54 = new javax.swing.JLabel();
        N55 = new javax.swing.JLabel();
        N56 = new javax.swing.JLabel();
        N57 = new javax.swing.JLabel();
        N58 = new javax.swing.JLabel();
        N59 = new javax.swing.JLabel();
        N60 = new javax.swing.JLabel();
        N61 = new javax.swing.JLabel();
        N62 = new javax.swing.JLabel();
        N63 = new javax.swing.JLabel();
        N64 = new javax.swing.JLabel();
        N65 = new javax.swing.JLabel();
        N66 = new javax.swing.JLabel();
        N67 = new javax.swing.JLabel();
        N68 = new javax.swing.JLabel();
        N69 = new javax.swing.JLabel();
        N70 = new javax.swing.JLabel();
        N71 = new javax.swing.JLabel();
        N72 = new javax.swing.JLabel();
        N73 = new javax.swing.JLabel();
        N74 = new javax.swing.JLabel();
        N75 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(11, 88, 132));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 5));
        jPanel1.setLayout(new java.awt.GridLayout(5, 15));

        N1.setBackground(new java.awt.Color(214, 204, 179));
        N1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N1.setForeground(new java.awt.Color(11, 88, 132));
        N1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N1.setText("1");
        N1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N1.setOpaque(true);
        jPanel1.add(N1);

        N2.setBackground(new java.awt.Color(11, 88, 132));
        N2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N2.setForeground(new java.awt.Color(220, 197, 156));
        N2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N2.setText("2");
        N2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N2.setOpaque(true);
        jPanel1.add(N2);

        N3.setBackground(new java.awt.Color(11, 88, 132));
        N3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N3.setForeground(new java.awt.Color(220, 197, 156));
        N3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N3.setText("3");
        N3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N3.setOpaque(true);
        jPanel1.add(N3);

        N4.setBackground(new java.awt.Color(11, 88, 132));
        N4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N4.setForeground(new java.awt.Color(220, 197, 156));
        N4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N4.setText("4");
        N4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N4.setOpaque(true);
        jPanel1.add(N4);

        N5.setBackground(new java.awt.Color(11, 88, 132));
        N5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N5.setForeground(new java.awt.Color(220, 197, 156));
        N5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N5.setText("5");
        N5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N5.setOpaque(true);
        jPanel1.add(N5);

        N6.setBackground(new java.awt.Color(11, 88, 132));
        N6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N6.setForeground(new java.awt.Color(220, 197, 156));
        N6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N6.setText("6");
        N6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N6.setOpaque(true);
        jPanel1.add(N6);

        N7.setBackground(new java.awt.Color(11, 88, 132));
        N7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N7.setForeground(new java.awt.Color(220, 197, 156));
        N7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N7.setText("7");
        N7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N7.setOpaque(true);
        jPanel1.add(N7);

        N8.setBackground(new java.awt.Color(11, 88, 132));
        N8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N8.setForeground(new java.awt.Color(220, 197, 156));
        N8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N8.setText("8");
        N8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N8.setOpaque(true);
        jPanel1.add(N8);

        N9.setBackground(new java.awt.Color(11, 88, 132));
        N9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N9.setForeground(new java.awt.Color(220, 197, 156));
        N9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N9.setText("9");
        N9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N9.setOpaque(true);
        jPanel1.add(N9);

        N10.setBackground(new java.awt.Color(11, 88, 132));
        N10.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N10.setForeground(new java.awt.Color(220, 197, 156));
        N10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N10.setText("10");
        N10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N10.setOpaque(true);
        jPanel1.add(N10);

        N11.setBackground(new java.awt.Color(11, 88, 132));
        N11.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N11.setForeground(new java.awt.Color(220, 197, 156));
        N11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N11.setText("11");
        N11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N11.setOpaque(true);
        jPanel1.add(N11);

        N12.setBackground(new java.awt.Color(11, 88, 132));
        N12.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N12.setForeground(new java.awt.Color(220, 197, 156));
        N12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N12.setText("12");
        N12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N12.setOpaque(true);
        jPanel1.add(N12);

        N13.setBackground(new java.awt.Color(11, 88, 132));
        N13.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N13.setForeground(new java.awt.Color(220, 197, 156));
        N13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N13.setText("13");
        N13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N13.setOpaque(true);
        jPanel1.add(N13);

        N14.setBackground(new java.awt.Color(11, 88, 132));
        N14.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N14.setForeground(new java.awt.Color(220, 197, 156));
        N14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N14.setText("14");
        N14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N14.setOpaque(true);
        jPanel1.add(N14);

        N15.setBackground(new java.awt.Color(11, 88, 132));
        N15.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N15.setForeground(new java.awt.Color(220, 197, 156));
        N15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N15.setText("15");
        N15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N15.setOpaque(true);
        jPanel1.add(N15);

        N16.setBackground(new java.awt.Color(11, 88, 132));
        N16.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N16.setForeground(new java.awt.Color(220, 197, 156));
        N16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N16.setText("16");
        N16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N16.setOpaque(true);
        jPanel1.add(N16);

        N17.setBackground(new java.awt.Color(11, 88, 132));
        N17.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N17.setForeground(new java.awt.Color(220, 197, 156));
        N17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N17.setText("17");
        N17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N17.setOpaque(true);
        jPanel1.add(N17);

        N18.setBackground(new java.awt.Color(11, 88, 132));
        N18.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N18.setForeground(new java.awt.Color(220, 197, 156));
        N18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N18.setText("18");
        N18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N18.setOpaque(true);
        jPanel1.add(N18);

        N19.setBackground(new java.awt.Color(11, 88, 132));
        N19.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N19.setForeground(new java.awt.Color(220, 197, 156));
        N19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N19.setText("19");
        N19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N19.setOpaque(true);
        jPanel1.add(N19);

        N20.setBackground(new java.awt.Color(11, 88, 132));
        N20.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N20.setForeground(new java.awt.Color(220, 197, 156));
        N20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N20.setText("20");
        N20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N20.setOpaque(true);
        jPanel1.add(N20);

        N21.setBackground(new java.awt.Color(11, 88, 132));
        N21.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N21.setForeground(new java.awt.Color(220, 197, 156));
        N21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N21.setText("21");
        N21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N21.setOpaque(true);
        jPanel1.add(N21);

        N22.setBackground(new java.awt.Color(11, 88, 132));
        N22.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N22.setForeground(new java.awt.Color(220, 197, 156));
        N22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N22.setText("22");
        N22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N22.setOpaque(true);
        jPanel1.add(N22);

        N23.setBackground(new java.awt.Color(11, 88, 132));
        N23.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N23.setForeground(new java.awt.Color(220, 197, 156));
        N23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N23.setText("23");
        N23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N23.setOpaque(true);
        jPanel1.add(N23);

        N24.setBackground(new java.awt.Color(11, 88, 132));
        N24.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N24.setForeground(new java.awt.Color(220, 197, 156));
        N24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N24.setText("24");
        N24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N24.setOpaque(true);
        jPanel1.add(N24);

        N25.setBackground(new java.awt.Color(11, 88, 132));
        N25.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N25.setForeground(new java.awt.Color(220, 197, 156));
        N25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N25.setText("25");
        N25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N25.setOpaque(true);
        jPanel1.add(N25);

        N26.setBackground(new java.awt.Color(11, 88, 132));
        N26.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N26.setForeground(new java.awt.Color(220, 197, 156));
        N26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N26.setText("26");
        N26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N26.setOpaque(true);
        jPanel1.add(N26);

        N27.setBackground(new java.awt.Color(11, 88, 132));
        N27.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N27.setForeground(new java.awt.Color(220, 197, 156));
        N27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N27.setText("27");
        N27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N27.setOpaque(true);
        jPanel1.add(N27);

        N28.setBackground(new java.awt.Color(11, 88, 132));
        N28.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N28.setForeground(new java.awt.Color(220, 197, 156));
        N28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N28.setText("28");
        N28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N28.setOpaque(true);
        jPanel1.add(N28);

        N29.setBackground(new java.awt.Color(11, 88, 132));
        N29.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N29.setForeground(new java.awt.Color(220, 197, 156));
        N29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N29.setText("29");
        N29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N29.setOpaque(true);
        jPanel1.add(N29);

        N30.setBackground(new java.awt.Color(11, 88, 132));
        N30.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N30.setForeground(new java.awt.Color(220, 197, 156));
        N30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N30.setText("30");
        N30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N30.setOpaque(true);
        jPanel1.add(N30);

        N31.setBackground(new java.awt.Color(11, 88, 132));
        N31.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N31.setForeground(new java.awt.Color(220, 197, 156));
        N31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N31.setText("31");
        N31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N31.setOpaque(true);
        jPanel1.add(N31);

        N32.setBackground(new java.awt.Color(11, 88, 132));
        N32.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N32.setForeground(new java.awt.Color(220, 197, 156));
        N32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N32.setText("32");
        N32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N32.setOpaque(true);
        jPanel1.add(N32);

        N33.setBackground(new java.awt.Color(11, 88, 132));
        N33.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N33.setForeground(new java.awt.Color(220, 197, 156));
        N33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N33.setText("33");
        N33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N33.setOpaque(true);
        jPanel1.add(N33);

        N34.setBackground(new java.awt.Color(11, 88, 132));
        N34.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N34.setForeground(new java.awt.Color(220, 197, 156));
        N34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N34.setText("34");
        N34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N34.setOpaque(true);
        jPanel1.add(N34);

        N35.setBackground(new java.awt.Color(11, 88, 132));
        N35.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N35.setForeground(new java.awt.Color(220, 197, 156));
        N35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N35.setText("35");
        N35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N35.setOpaque(true);
        jPanel1.add(N35);

        N36.setBackground(new java.awt.Color(11, 88, 132));
        N36.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N36.setForeground(new java.awt.Color(220, 197, 156));
        N36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N36.setText("36");
        N36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N36.setOpaque(true);
        jPanel1.add(N36);

        N37.setBackground(new java.awt.Color(11, 88, 132));
        N37.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N37.setForeground(new java.awt.Color(220, 197, 156));
        N37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N37.setText("37");
        N37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N37.setOpaque(true);
        jPanel1.add(N37);

        N38.setBackground(new java.awt.Color(11, 88, 132));
        N38.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N38.setForeground(new java.awt.Color(220, 197, 156));
        N38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N38.setText("38");
        N38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N38.setOpaque(true);
        jPanel1.add(N38);

        N39.setBackground(new java.awt.Color(11, 88, 132));
        N39.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N39.setForeground(new java.awt.Color(220, 197, 156));
        N39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N39.setText("39");
        N39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N39.setOpaque(true);
        jPanel1.add(N39);

        N40.setBackground(new java.awt.Color(11, 88, 132));
        N40.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N40.setForeground(new java.awt.Color(220, 197, 156));
        N40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N40.setText("40");
        N40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N40.setOpaque(true);
        jPanel1.add(N40);

        N41.setBackground(new java.awt.Color(11, 88, 132));
        N41.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N41.setForeground(new java.awt.Color(220, 197, 156));
        N41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N41.setText("41");
        N41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N41.setOpaque(true);
        jPanel1.add(N41);

        N42.setBackground(new java.awt.Color(11, 88, 132));
        N42.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N42.setForeground(new java.awt.Color(220, 197, 156));
        N42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N42.setText("42");
        N42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N42.setOpaque(true);
        jPanel1.add(N42);

        N43.setBackground(new java.awt.Color(11, 88, 132));
        N43.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N43.setForeground(new java.awt.Color(220, 197, 156));
        N43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N43.setText("43");
        N43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N43.setOpaque(true);
        jPanel1.add(N43);

        N44.setBackground(new java.awt.Color(11, 88, 132));
        N44.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N44.setForeground(new java.awt.Color(220, 197, 156));
        N44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N44.setText("44");
        N44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N44.setOpaque(true);
        jPanel1.add(N44);

        N45.setBackground(new java.awt.Color(11, 88, 132));
        N45.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N45.setForeground(new java.awt.Color(220, 197, 156));
        N45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N45.setText("45");
        N45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N45.setOpaque(true);
        jPanel1.add(N45);

        N46.setBackground(new java.awt.Color(11, 88, 132));
        N46.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N46.setForeground(new java.awt.Color(220, 197, 156));
        N46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N46.setText("46");
        N46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N46.setOpaque(true);
        jPanel1.add(N46);

        N47.setBackground(new java.awt.Color(11, 88, 132));
        N47.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N47.setForeground(new java.awt.Color(220, 197, 156));
        N47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N47.setText("47");
        N47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N47.setOpaque(true);
        jPanel1.add(N47);

        N48.setBackground(new java.awt.Color(11, 88, 132));
        N48.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N48.setForeground(new java.awt.Color(220, 197, 156));
        N48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N48.setText("48");
        N48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N48.setOpaque(true);
        jPanel1.add(N48);

        N49.setBackground(new java.awt.Color(11, 88, 132));
        N49.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N49.setForeground(new java.awt.Color(220, 197, 156));
        N49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N49.setText("49");
        N49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N49.setOpaque(true);
        jPanel1.add(N49);

        N50.setBackground(new java.awt.Color(11, 88, 132));
        N50.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N50.setForeground(new java.awt.Color(220, 197, 156));
        N50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N50.setText("50");
        N50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N50.setOpaque(true);
        jPanel1.add(N50);

        N51.setBackground(new java.awt.Color(11, 88, 132));
        N51.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N51.setForeground(new java.awt.Color(220, 197, 156));
        N51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N51.setText("51");
        N51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N51.setOpaque(true);
        jPanel1.add(N51);

        N52.setBackground(new java.awt.Color(11, 88, 132));
        N52.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N52.setForeground(new java.awt.Color(220, 197, 156));
        N52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N52.setText("52");
        N52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N52.setOpaque(true);
        jPanel1.add(N52);

        N53.setBackground(new java.awt.Color(11, 88, 132));
        N53.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N53.setForeground(new java.awt.Color(220, 197, 156));
        N53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N53.setText("53");
        N53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N53.setOpaque(true);
        jPanel1.add(N53);

        N54.setBackground(new java.awt.Color(11, 88, 132));
        N54.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N54.setForeground(new java.awt.Color(220, 197, 156));
        N54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N54.setText("54");
        N54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N54.setOpaque(true);
        jPanel1.add(N54);

        N55.setBackground(new java.awt.Color(11, 88, 132));
        N55.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N55.setForeground(new java.awt.Color(220, 197, 156));
        N55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N55.setText("55");
        N55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N55.setOpaque(true);
        jPanel1.add(N55);

        N56.setBackground(new java.awt.Color(11, 88, 132));
        N56.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N56.setForeground(new java.awt.Color(220, 197, 156));
        N56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N56.setText("56");
        N56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N56.setOpaque(true);
        jPanel1.add(N56);

        N57.setBackground(new java.awt.Color(11, 88, 132));
        N57.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N57.setForeground(new java.awt.Color(220, 197, 156));
        N57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N57.setText("57");
        N57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N57.setOpaque(true);
        jPanel1.add(N57);

        N58.setBackground(new java.awt.Color(11, 88, 132));
        N58.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N58.setForeground(new java.awt.Color(220, 197, 156));
        N58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N58.setText("58");
        N58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N58.setOpaque(true);
        jPanel1.add(N58);

        N59.setBackground(new java.awt.Color(11, 88, 132));
        N59.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N59.setForeground(new java.awt.Color(220, 197, 156));
        N59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N59.setText("59");
        N59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N59.setOpaque(true);
        jPanel1.add(N59);

        N60.setBackground(new java.awt.Color(11, 88, 132));
        N60.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N60.setForeground(new java.awt.Color(220, 197, 156));
        N60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N60.setText("60");
        N60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N60.setOpaque(true);
        jPanel1.add(N60);

        N61.setBackground(new java.awt.Color(11, 88, 132));
        N61.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N61.setForeground(new java.awt.Color(220, 197, 156));
        N61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N61.setText("61");
        N61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N61.setOpaque(true);
        jPanel1.add(N61);

        N62.setBackground(new java.awt.Color(11, 88, 132));
        N62.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N62.setForeground(new java.awt.Color(220, 197, 156));
        N62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N62.setText("62");
        N62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N62.setOpaque(true);
        jPanel1.add(N62);

        N63.setBackground(new java.awt.Color(11, 88, 132));
        N63.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N63.setForeground(new java.awt.Color(220, 197, 156));
        N63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N63.setText("63");
        N63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N63.setOpaque(true);
        jPanel1.add(N63);

        N64.setBackground(new java.awt.Color(11, 88, 132));
        N64.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N64.setForeground(new java.awt.Color(220, 197, 156));
        N64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N64.setText("64");
        N64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N64.setOpaque(true);
        jPanel1.add(N64);

        N65.setBackground(new java.awt.Color(11, 88, 132));
        N65.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N65.setForeground(new java.awt.Color(220, 197, 156));
        N65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N65.setText("65");
        N65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N65.setOpaque(true);
        jPanel1.add(N65);

        N66.setBackground(new java.awt.Color(11, 88, 132));
        N66.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N66.setForeground(new java.awt.Color(220, 197, 156));
        N66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N66.setText("66");
        N66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N66.setOpaque(true);
        jPanel1.add(N66);

        N67.setBackground(new java.awt.Color(11, 88, 132));
        N67.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N67.setForeground(new java.awt.Color(220, 197, 156));
        N67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N67.setText("67");
        N67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N67.setOpaque(true);
        jPanel1.add(N67);

        N68.setBackground(new java.awt.Color(11, 88, 132));
        N68.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N68.setForeground(new java.awt.Color(220, 197, 156));
        N68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N68.setText("68");
        N68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N68.setOpaque(true);
        jPanel1.add(N68);

        N69.setBackground(new java.awt.Color(11, 88, 132));
        N69.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N69.setForeground(new java.awt.Color(220, 197, 156));
        N69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N69.setText("69");
        N69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N69.setOpaque(true);
        jPanel1.add(N69);

        N70.setBackground(new java.awt.Color(11, 88, 132));
        N70.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N70.setForeground(new java.awt.Color(220, 197, 156));
        N70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N70.setText("70");
        N70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N70.setOpaque(true);
        jPanel1.add(N70);

        N71.setBackground(new java.awt.Color(11, 88, 132));
        N71.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N71.setForeground(new java.awt.Color(220, 197, 156));
        N71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N71.setText("71");
        N71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N71.setOpaque(true);
        jPanel1.add(N71);

        N72.setBackground(new java.awt.Color(11, 88, 132));
        N72.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N72.setForeground(new java.awt.Color(220, 197, 156));
        N72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N72.setText("72");
        N72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N72.setOpaque(true);
        jPanel1.add(N72);

        N73.setBackground(new java.awt.Color(11, 88, 132));
        N73.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N73.setForeground(new java.awt.Color(220, 197, 156));
        N73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N73.setText("73");
        N73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N73.setOpaque(true);
        jPanel1.add(N73);

        N74.setBackground(new java.awt.Color(11, 88, 132));
        N74.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N74.setForeground(new java.awt.Color(220, 197, 156));
        N74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N74.setText("74");
        N74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N74.setOpaque(true);
        jPanel1.add(N74);

        N75.setBackground(new java.awt.Color(11, 88, 132));
        N75.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        N75.setForeground(new java.awt.Color(220, 197, 156));
        N75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N75.setText("75");
        N75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 204, 179), 3));
        N75.setOpaque(true);
        jPanel1.add(N75);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel N1;
    private javax.swing.JLabel N10;
    private javax.swing.JLabel N11;
    private javax.swing.JLabel N12;
    private javax.swing.JLabel N13;
    private javax.swing.JLabel N14;
    private javax.swing.JLabel N15;
    private javax.swing.JLabel N16;
    private javax.swing.JLabel N17;
    private javax.swing.JLabel N18;
    private javax.swing.JLabel N19;
    private javax.swing.JLabel N2;
    private javax.swing.JLabel N20;
    private javax.swing.JLabel N21;
    private javax.swing.JLabel N22;
    private javax.swing.JLabel N23;
    private javax.swing.JLabel N24;
    private javax.swing.JLabel N25;
    private javax.swing.JLabel N26;
    private javax.swing.JLabel N27;
    private javax.swing.JLabel N28;
    private javax.swing.JLabel N29;
    private javax.swing.JLabel N3;
    private javax.swing.JLabel N30;
    private javax.swing.JLabel N31;
    private javax.swing.JLabel N32;
    private javax.swing.JLabel N33;
    private javax.swing.JLabel N34;
    private javax.swing.JLabel N35;
    private javax.swing.JLabel N36;
    private javax.swing.JLabel N37;
    private javax.swing.JLabel N38;
    private javax.swing.JLabel N39;
    private javax.swing.JLabel N4;
    private javax.swing.JLabel N40;
    private javax.swing.JLabel N41;
    private javax.swing.JLabel N42;
    private javax.swing.JLabel N43;
    private javax.swing.JLabel N44;
    private javax.swing.JLabel N45;
    private javax.swing.JLabel N46;
    private javax.swing.JLabel N47;
    private javax.swing.JLabel N48;
    private javax.swing.JLabel N49;
    private javax.swing.JLabel N5;
    private javax.swing.JLabel N50;
    private javax.swing.JLabel N51;
    private javax.swing.JLabel N52;
    private javax.swing.JLabel N53;
    private javax.swing.JLabel N54;
    private javax.swing.JLabel N55;
    private javax.swing.JLabel N56;
    private javax.swing.JLabel N57;
    private javax.swing.JLabel N58;
    private javax.swing.JLabel N59;
    private javax.swing.JLabel N6;
    private javax.swing.JLabel N60;
    private javax.swing.JLabel N61;
    private javax.swing.JLabel N62;
    private javax.swing.JLabel N63;
    private javax.swing.JLabel N64;
    private javax.swing.JLabel N65;
    private javax.swing.JLabel N66;
    private javax.swing.JLabel N67;
    private javax.swing.JLabel N68;
    private javax.swing.JLabel N69;
    private javax.swing.JLabel N7;
    private javax.swing.JLabel N70;
    private javax.swing.JLabel N71;
    private javax.swing.JLabel N72;
    private javax.swing.JLabel N73;
    private javax.swing.JLabel N74;
    private javax.swing.JLabel N75;
    private javax.swing.JLabel N8;
    private javax.swing.JLabel N9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
