/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author llean
 */
public class IFrmCarton extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmCarton
     */
    public IFrmCarton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Matriz = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Matriz.setBackground(new java.awt.Color(242, 212, 147));
        Matriz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 75, 42), 5));
        Matriz.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(Matriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 520, 400));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carton.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel Matriz;
    // End of variables declaration//GEN-END:variables
}
